### ISSUE TITLE
If variable is 'true' crash

### ISSUE THREAD

**Issue by KenneyNL** [chrismaltby/gb-studio#211] opened 2019-06-07 23:57 UTC
**Describe the bug**
The section of code "If variable is 'true'" will not function and crash the game. The code can be found on the "Dice" scene, on start of scene at the very bottom.

**To Reproduce**
1. Open the project, start the game
2. Walk to the right
3. Talk to the NPC
4. Dice will be thrown
5. Once the user gets a choice between "Roll" and "Stand"...
6. **"Roll" will do nothing**
7. **"Stand" will crash the game**

**Expected behavior**
The actions within the if statement should function.

**Platform (please complete the following information):**
 - OS: Windows 10
 - App version: 1.1.0

[apocadice_src.zip](https://github.com/chrismaltby/gb-studio/files/3267910/apocadice_src.zip)

**Comment by RichardULZ** [comment] 2019-06-08 00:54
[InvokeBadMultichoice.zip](https://github.com/chrismaltby/gb-studio/files/3267960/InvokeBadMultichoice.zip)

Here's a stripped down version of the bug, and a work around.

Issue is caused by actor invoke (used to roll their dice), when actor invoke returns to the original actor, script pointers/script actor's are not re set to the original, and "branch if" events that require correct pointers fail.

Work around is to re invoke an actor, and use a variable to jump between stages of your code.
Or invoke invisible actors that have each part of the code in them.

Point is, if you want to branch with if, and have used an actor invoke earlier, you can not currently branch on auto return, as it still thinks you're running as the invoked actor.

**Comment by chrismaltby** [comment] 2019-06-25 11:50
I've merged your fix @RichardULZ seems both the example project you provided and the one @KenneyNL included are no longer crashing in the development builds.

**Closed by chrismaltby** 2019-06-25 11:50 UTC
Labels: bug
