### ISSUE TITLE
[2.0.0 Beta 2] Different size background doesn't update editable area until restart

### ISSUE THREAD

**Issue by JamesParkNINJA** [chrismaltby/gb-studio#559] opened 2020-09-22 10:29 UTC
**Describe the bug**
When you switch to a background that's a different size from the default a new scene picks, the new size doesn't get auto-calc'd properly and triggers snap to the bottom of the old size (until you close and reopen).

**To Reproduce**
1. Create a new Scene (by default it would take a 160x144 background)
2. Switch background to larger size (160x288 in my case)
3. Add an actor/trigger to the scene
4. Try to move it to the bottom of the scene
5. Editable parts of scene still locked to old background size

**Expected behavior**
The editor should update the editable area based on background size selected

**Screenshots**
![ITD-error-003](https://user-images.githubusercontent.com/6178652/93871613-d544c700-fcc6-11ea-8760-9373919f703b.gif)

**Platform (please complete the following information):**
 - OS: Windows 10
 - App version 2.0.0 Beta 2

**Comment by RichardULZ** [comment] 2020-09-22 11:05
Oh no is this related to the older scene hasn't updated dimensions from replaced image bug? #386

Hmm, seems not, I have replicated your new bug by Switching a scenes background from the dropdown options for the scene within the editor, not externally like in #386 (which seems to be fixed? will investigate)

The scene must be small when placed in the background, and be changed to a larger background to reproduce the bug. Copying and pasting the scene does not fix the issue, Reload assets does not fix this issue, saving and using File Open does solve the issue for placed scenes.

**Comment by chrismaltby** [comment] 2020-09-25 19:47
This is pretty embarrassing bug introduced when I rewrote a lot of the backend recently, I actually did write a load of tests around this area but missed writing a test for this specific bit of functionality :-(

I've just merged a two line fix in #566  could you confirm this works for you now with the latest dev build?

**Comment by chrismaltby** [comment] 2020-09-27 18:42
This fix is now deployed in beta3 :-)

**Closed by chrismaltby** 2020-09-27 18:42 UTC
Labels: bug
