### ISSUE TITLE
The new dialogue event when set to instand doesn't show the text in consistent timing

### ISSUE THREAD

**Issue by Antimetaknight** [chrismaltby/gb-studio#1571] opened 2024-09-05 20:37 UTC
The latests updated dialogue event when set to instant (open,close,draw speed) will show the text in variable times, from instant to hanging a bit and then showing the text. This happen at random but in big dialogue scenes becomes visible. Note that 4.0 and earlier versions don't have this problem. 

To reproduce add event "set text animation speed" and set everything to instant. Then add event "display dialogue" with many dialogues. Either a dialogue with multiple dialogues or multiple dialogue events will do. I suggest around forty two line dialogues. Also adding an avatar feels like it makes it worse. For comparison the same can be done in 4.0 to identify the problem.

The older dialogue event seems to have consistent timing. The new one doesn't.
I added two roms with test dialogues from a game I am working. Just mush a to work through the dialogues.

[4.0 and 4.1.1 test dialogues.zip](https://github.com/user-attachments/files/16899975/4.0.and.4.1.1.test.dialogues.zip)

**Comment by chrismaltby** [comment] 2024-09-06 13:57
Thanks @Antimetaknight I've identified what I believe to be the cause of this issue and have pushed a fix which will be available in a development build at https://github.com/chrismaltby/gb-studio/actions/runs/10739668949

**Comment by chrismaltby** [comment] 2024-09-06 13:58
Oh actually, the tests are failing so that link won't work. I'll fix the tests and provide a new dev build url

**Comment by chrismaltby** [comment] 2024-09-06 15:20
This build should fix the issues you were seeing @Antimetaknight https://github.com/chrismaltby/gb-studio/actions/runs/10740304730

**Comment by Antimetaknight** [comment] 2024-09-07 16:09
After some testing, the fix works perfectly! Great work @chrismaltby !

**Closed** 2024-09-09 12:24 UTC
Labels: bug
