### ISSUE TITLE
Better mouse controls in the Game World editor

### ISSUE THREAD

**Issue by DuendeInexistente** [chrismaltby/gb-studio#101] opened 2019-05-01 00:53 UTC
In most editors of this type, holding the middle/right mouse button allows you to hover arround the document (Without needing to use the scrollbars) and turning the wheel lets you zoom in and out.

It's a very small feature, but it improves UX massively. Is there any chance of it being added?

**Comment by thomas-alrek** [comment] 2019-05-01 01:12
Duplicate of #17

**Comment by RichardULZ** [comment] 2019-05-01 06:58
Already done in development build.
https://github.com/chrismaltby/gb-studio/commit/5d0b40821fa198e547cfb315edef28ad9ee1ca82

**Closed** 2019-05-01 07:11 UTC
