### ISSUE TITLE
Problem with [Actor set position to (TileX,TileY)] in a script

### ISSUE THREAD

**Issue by Antimetaknight** [chrismaltby/gb-studio#1463] opened 2024-06-24 23:56 UTC
If you put in a script [Actor set position to (TileX,TileY)] where TileX and TileY are the position of any actor (using actor properties) they seem to use the player's X and Y. This was previously working so it is somewhat new (observed in the lastest version 4.0).
 
 To reproduce make a script where you add the actor as part of it. Use [Actor set position to (Actor.TileX,Actor.TileY)]. Make sure that the actor is in different X and Y from the player. In the scene make an Attach script to button and add a call script in it, and call the script you made previously. Running the game, when you push the button the actor will position itself to the same X and Y as the player.

**Comment by chrismaltby** [comment] 2024-06-27 14:52
Hi @Antimetaknight I've identified a few places that I think could be causing this, I need to do some more testing.

Would you be able to provide a zip containing a sample project showing this issue so that I can confirm any changes I make fix the issue?

**Comment by Antimetaknight** [comment] 2024-06-27 15:36
Hi @chrismaltby ! I made a sample project. When you press any button actor 1 is supposed to go to actor 2 but it will always go to the player.

[bug.zip](https://github.com/user-attachments/files/16016409/bug.zip)

**Comment by chrismaltby** [comment] 2024-06-28 17:35
Thanks @Antimetaknight That's perfect. I think I've identified the cause of the problem and have a fix but I need to write some tests to confirm that nothing else gets broken due to this change

If you'd like to test the fix on your project I've made a debug build available here:
https://github.com/chrismaltby/gb-studio/actions/runs/9715758601

Once I've written some more tests I'll merge this fix for the next release

**Comment by Antimetaknight** [comment] 2024-06-28 19:17
After doing some testing I can confirm that the sample project and the project I am currently working on, do work as intended! 
Thank you @chrismaltby !

**Comment by chrismaltby** [comment] 2024-07-02 15:41
Thanks for confirming @Antimetaknight I've merged this fix into the develop branch and it will be included in the next official release

**Closed by chrismaltby** 2024-07-02 15:41 UTC
Labels: bug
