### ISSUE TITLE
[mobile] Dpad controls vanish after display is turned off

### ISSUE THREAD

**Issue by therocco** [chrismaltby/gb-studio#234] opened 2019-06-26 20:31 UTC
When running your game on a mobile device if your screen times out, or you turn your display off and turn it back on, the dpad and input buttons will turn off and remove themselves from the DOM.

**To Reproduce**
1. Export game for web
2. Run game in local development server
3. Open up URL for local dev game on a mobile device (tested on Android)
4. Turn the display off and let it sit for a few seconds
5. Turn the display back on and the controls should vanish

**Expected behavior**
Dpad does not remove itself from the DOM

**Screenshots**
![Screenshot_20190626-132352](https://user-images.githubusercontent.com/801056/60212639-92234c00-9816-11e9-9060-54388ade3aa8.png)
![Screenshot_20190626-132415](https://user-images.githubusercontent.com/801056/60212640-92234c00-9816-11e9-9a7f-0ac0657a3c1f.png)

**Platform (please complete the following information):**
 - OS: Android
 - App version: 1.1.0
 - Browser: Chrome v75.0.3770.101

**Comment by RichardULZ** [comment] 2019-10-26 04:40
I've tried almost everything but could not replicate this issue.

2 separate android devices (oneplus3T, Huwawei Y330)
Using gbs1.1 web builds on local hosting, 
Tested on both Chrome and Firefox for android,
Lock screen or no lock screen, natural screen time out or using power button, 
Any pause length between seconds and minutes before unlocking.

@therocco Could you provide any more details on your device and maybe a .zip of a known broken project with web build?

**Comment by chrismaltby** [comment] 2019-11-11 21:43
Hi @RichardULZ thanks for looking into this, I've also been unable to reproduce the issue.

I spotted a similar issue on iPad where if using a keyboard the touch controls become hidden and won't restore if switching to using the touch screen. I can only imagine that this is related as the only code that hides the on screen controls after the page has loaded was in the window.onkeydown function of `controls.js`, with the change in fce334db0b08b29ff96adb1e170e5fb581c2f82f they should come back after the first screen touch.

I'm going to close this for now.

**Closed by chrismaltby** 2019-11-11 21:43 UTC
Labels: bug
