### ISSUE TITLE
[Request] Actor spawner

### ISSUE THREAD

**Issue by dyvap** [chrismaltby/gb-studio#73] opened 2019-04-26 16:51 UTC
I think that we need an actor spawner to make projectiles and things like that

**Comment by DerekLF** [comment] 2019-04-26 17:03
You've uploaded 4 separate issues. Which could've been placed into a single one. This would be hard because of the Actor limit. And, kind of a duplicate of this one #33. Except you want to shoot it 
But making an IF loop with actor XY variable location(coming soon i think) and then increment by 1. and make it disappear a certain location.

**Comment by chrismaltby** [comment] 2019-04-26 19:09
I think the only way to do this would be to create actors that you hide on scene load, and then reenable them as needed.

As Derek says the actor limit makes this a little difficult to do more than that. But to actually shoot projectiles would require a few more things to be in place too.

On a side note @DerekLF I've not been using Github for more than solo projects before the last few days, what's common practice here on having multiple issues. My first thought is I'd prefer each thing to be separate then they can be referred to and closed with commits that resolve them. Multiple issues in the same same post would mean some issues would stay open when 90% of the requests were implemented. Not sure which is best.

I'm closing because it is similar to #33 but with the addition of a bit of #69

**Closed by chrismaltby** 2019-04-26 19:09 UTC

**Comment by DerekLF** [comment] 2019-04-26 19:38
@chrismaltby aha, oke well. It's your github page ;) 
But the issues page could also get a bit to crowded because people are spamming issues in separate topics. Which means, some of the issues will be pushed to the second page and never seen again.

**Comment by thomas-alrek** [comment] 2019-04-26 23:56
Chris, it would be a good idea to add a /.github/ISSUE_TEMPLATE.md

There you can add a checklist or form that should be filled when filing a new issue
