### ISSUE TITLE
Actor Moving Off Top Of Scene On Init Causes Large Pause/Freeze During Scene Init.

### ISSUE THREAD

**Issue by MaxBeforeTheOne** [chrismaltby/gb-studio#1450] opened 2024-06-13 18:16 UTC
**Describe the bug**
Having an actor move off of the top of a scene on it's On Init script causes a large pause/freeze before the scene starts.

**To Reproduce**
1. Place an actor at the top of the scene.
2. Give them a script to move them up off of the scene in it's On Init script. (Self Move Relative By {0,-1})
3. Press play and load the scene.

**Expected behavior**
I don't know what should be expected other than the large pause not occurring. The only reason why this occurred was because I accidentally left an On Init script on an actor after copying that actor from a different scene that needed to be moved on init. This issue does not happen in GBS 3.2.1.

**Platform (please complete the following information):**
 - OS: Windows 10?
 - App version: v4.0.0-rc.2

**Additional context**
At first I thought the issue had something to do with the Auto Fade In, and I was somehow able to disable the Auto Fade In and have there be no warning about it in a scene, but I'm not able to recreate this. Last night I also got the scene loading fine just by having the Auto Fade In enabled, even with the actor going off the top of the scene, but I'm now also not able to recreate this.

**Comment by attackemartin** [comment] 2024-06-19 20:11
can confirm this bug

**Comment by nielsderijk** [comment] 2024-06-19 23:33
Moving an actor always pauses other scripts if done on Init. Either Set the position of your Actor directly, adjust its movement speed OR use an On Update script.

**Comment by attackemartin** [comment] 2024-09-02 18:54
here is an example project showcasing the bug.
If you go to the right trigger on the bottom, the script runs through just fine.
If you however jump to the top to the top trigger, the script has some issues.
[bug-edge-reboot.zip](https://github.com/user-attachments/files/16840636/bug-edge-reboot.zip)
Project is made in 4.1, but the bug was also there in 4.0 and I think earlier as well.

To give some more informations:
In my game, if you die, I have a little die animation which lifts the player up 3 tiles. If that happens too near to the top, then I ran into this bug, and the animation takes many seconds and the player sprite flies from the bottom to the top of the screen after some seconds.

**Comment by chrismaltby** [comment] 2024-09-03 08:40
Thanks @attackemartin that project was very useful. I believe the problem is around here in the code that handles updating the actors position while a "Move To" or "Move Relative" event is running

https://github.com/chrismaltby/gb-studio/blob/5272935786161ebf0ccbd0dbd4488150ff7f3c15/appData/src/gb/src/core/vm_actor.c#L187-L188

https://github.com/chrismaltby/gb-studio/blob/5272935786161ebf0ccbd0dbd4488150ff7f3c15/appData/src/gb/src/core/vm_actor.c#L204-L209
As the player position is stored as an unsigned 16-bit value when it is being moved below `0` it wraps to `65535` so rather than overshooting above the destination it looks like it's below. I wouldn't be surprised if you waited long enough the player might even appear from the bottom of the screen continuing to move upwards indefinitely.

The simple solution would be to store the position in 16-bit signed value (giving a range of `-32768` to `+32767`) but I'd need to check this doesn't cause any issues with anything else. My first concern was that this effectively halves the max X and max Y values possible but if my maths is right we might still be okay. The max scene width is `255` tiles, and a position is stored with 4 bits giving the subpixel position, 3 bits giving the pixel offset in a tile and the remaining 9 bits bits giving the tile position, removing 1 bit to for the sign of the value still gives 8 bits for the tile position, exactly how many are needed. There's quite a lot of code in the engine that would need updating though and lots to test for breaking changes.

If you want to try this yourself you can try ejecting the game engine and changing `gbs_types.h` so that `typedef struct actor_t` uses `point16_t pos;` rather than `upoint16_t` then you'll have to fix every error you get each time you try building (it should give you the file and line number) which will mostly be a case of replacing every `upoint16_t` with ``point16_t` (maybe even a mass find/replace would work).

**Comment by chrismaltby** [comment] 2024-09-04 17:09
I've made this game engine change here f090e3a22f391056e1411f7ce22029c84422609d
A dev build will be available at: https://github.com/chrismaltby/gb-studio/actions/runs/10706251753
In testing your project with this version @attackemartin I'm no longer seeing this issue

**Comment by attackemartin** [comment] 2024-09-08 15:18
@chrismaltby seems to be fixed! Awesome! Thank you

**Comment by chrismaltby** [comment] 2024-09-09 12:51
The fix for this issue is included in GB Studio 4.1.2 which I've just released today :-) https://chrismaltby.itch.io/gb-studio

**Closed by chrismaltby** 2024-09-09 12:51 UTC
Labels: bug
