### ISSUE TITLE
Wrong Warp or something like that in sample game

### ISSUE THREAD

**Issue by arthuro555** [chrismaltby/gb-studio#233] opened 2019-06-26 17:25 UTC
**Describe the bug**
It is possible to warp to random scenes in the sample game.

**To Reproduce**
1. Start the game and enter a state where you can use the quest menu
2. Push on right or left and don't stop pushing
3. Spam a and start until you see the menu vanishing and reapearing without seeing eaven just one frame with the player and the scene where you should be
4. Exit the menu and see that you are in another random scene in the upper right corner.

**Expected behavior**
The menu should just close and open and not warp you arround.

**Platform (please complete the following information):**
 - OS: Windows 10
 - App version: 1.1.0

**Comment by DerekLF** [comment] 2019-06-29 21:50
I just tested it(you don't actually have to press a direction button), It's indeed weird. Looks like it could have something to do with the Warping of backgrounds in combination with the previous location and scene being stored with _Scene: Restore Previous From Stack_ 
It's one way of getting to the space dog 😝

**Comment by chrismaltby** [comment] 2019-07-01 11:32
Weird! Looks like all you need to do to reproduce this is press Start while the Menu scene is fading out which causes it to return back to the Menu scene but when you leave your X/Y position has been reset and the scene index is one higher than it was previously.

Reminds me of the Screen Warp Glitch in Link's Awakening! https://zelda.gamepedia.com/Glitches_in_Link%27s_Awakening#Screen_Warp_Glitch

**Comment by chrismaltby** [comment] 2019-07-01 12:57
Should be fixed now with fd109b203d83407bdb3318cc426185321859abff

**Closed** 2019-09-13 22:39 UTC
Labels: bug
