### ISSUE TITLE
Everything displaying as a garbled mess, and custom sprite sheet not displaying! 

### ISSUE THREAD

**Issue by PaperVb64** [chrismaltby/gb-studio#991] opened 2022-01-13 14:07 UTC
Describe the bug
Text boxes displaying as random blocks of the logo (i'm using the latest version, not beta) and sprite sheet i got from spriters resource not showing. 

To Reproduce
1. Add a text box (any message will do)
2. Add a custom sprite
3. Add a logo screen (again, it could be copyrighted, it doesn't matter
4. Run the game
5. Run the game
6. Textbox shows up with a mangled text box with snippets of the logo background
7. Player Sprite doesn't even show up   

Expected behaviour
Textbox sows up as normal, and sprite works as per usual.

**Screenshots**
![image](https://user-images.githubusercontent.com/94991205/149346797-d67a0873-08e8-4955-ba9d-deb848195884.png)
![image](https://user-images.githubusercontent.com/94991205/149346827-82443b0e-d1c6-415a-a56b-25079da0efef.png)

**Platform (please complete the following information):**
 - OS: Chrome OS Version 99.0.4807.0 (Official Build) dev (64-bit)
 - App version: GB Studio 3.0.2 (Official) 

Additional context
I used this sprite sheet:
![image](https://user-images.githubusercontent.com/94991205/149347624-588a049a-a9b2-4b02-89e8-8b76b09e598b.png)
[Credit to BlueBur64]

**Comment by PaperVb64** [comment] 2022-01-13 14:25
Would the sprite sheet have to do anything with it? (PS: i've had issues on windows 10 with this sprite sheet before. It did show up though. It just came out mangled).

**Comment by pau-tomas** [comment] 2022-01-13 15:04
Logo scenes don't support text events.

**Comment by codyjb** [comment] 2022-01-13 15:35
Recommend closing @chrismaltby, not a bug

**Comment by PaperVb64** [comment] 2022-01-14 18:19
oooooooooooooooooooooooohh.
________________________________

**Closed** 2022-09-01 04:22 UTC
Labels: bug
