### ISSUE TITLE
[Help Needed] Unable to Run Game

### ISSUE THREAD

**Issue by AsherGomez** [chrismaltby/gb-studio#57] opened 2019-04-25 01:10 UTC
Hi, I'm making a game and I'm unable to run it, I get this error:
![Error](https://user-images.githubusercontent.com/45052326/56703057-c1a9c100-66cc-11e9-8754-7a6191372e4f.png)
What do I do?

**Comment by chrismaltby** [comment] 2019-04-25 08:21
Hi Asher, this is a duplicate of https://github.com/chrismaltby/gb-studio/issues/6 so I'm going to close this one, if you don't mind zipping up a small example project where there is happening and attaching to that issue I can look into it.

**Closed by chrismaltby** 2019-04-25 08:21 UTC

**Comment by AsherGomez** [comment] 2019-04-25 12:02
Here:
[Roboventure.zip](https://github.com/chrismaltby/gb-studio/files/3116757/Roboventure.zip)

**Comment by AsherGomez** [comment] 2019-04-25 13:04
I'm on a MacBook.

**Comment by chrismaltby** [comment] 2019-04-25 13:10
Hi Asher,

The problem was your L1.png which was 256px by 257px (1px taller than is
currently allowed), I cropped your image and the game runs now.
Attached a fixed version of the project.
I definitely need to improve the error message here so that it's clear
what's happening but if you stick to sizes with multiples of 8 you should
be fine!
https://github.com/chrismaltby/gb-studio/issues/51 is the issue I've set
for handling this.

Looks great by the way!

Thanks,
Chris


[image: Screen Shot 2019-04-25 at 2.05.07 PM.png]

**Comment by chrismaltby** [comment] 2019-04-25 13:24
Hi Asher,

The problem was your L1.png which was 256px by 257px (1px taller than is currently allowed), I cropped your image and the game runs now.

Attached a fixed version of the project.

I definitely need to improve the error message here so that it's clear what's happening but if you stick to sizes with multiples of 8 you should be fine! #51 is the issue I've set for handling this.

Looks great by the way!

[Roboventure_fixed.zip](https://github.com/chrismaltby/gb-studio/files/3117048/Roboventure_fixed.zip)
<img width="592" alt="Screen Shot 2019-04-25 at 2 05 07 PM" src="https://user-images.githubusercontent.com/16776042/56739038-c2dafc80-6765-11e9-9a06-8620c3ed670b.png">

**Comment by AsherGomez** [comment] 2019-04-25 13:29
Thanks!
