### ISSUE TITLE
[Request] Change sprites and Play animation event

### ISSUE THREAD

**Issue by dyvap** [chrismaltby/gb-studio#72] opened 2019-04-26 16:49 UTC
I think that we need a way to change the actor's sprite like the player sprite changer and an event to play animations.

**Comment by DerekLF** [comment] 2019-04-26 17:04
You've uploaded 4 separate issues. Which could've been placed into a single one. Also duplicate of this one #8

**Closed** 2019-04-26 19:11 UTC
