### ISSUE TITLE
Caret is mis-located when multibyte characters entered in text box input fields

### ISSUE THREAD

**Issue by tomo666** [chrismaltby/gb-studio#1467] opened 2024-06-25 14:39 UTC
**Describe the bug**
In multi-byte environment such as Japanese, when using IME input to insert non-alphabetic (MBSC) characters with text boxes, the actual caret position is located at a different place.
This issue is found in both MacOS and Windows. Tested in Sonoma 14 and Windows 11. This not only occurs in dialogue event text boxes, but also when typing into math equations.

![BugReport_GBS_caret_issue_20260625](https://github.com/chrismaltby/gb-studio/assets/3715832/347bffff-e3d3-4358-a677-f1a5182e155c)

**To Reproduce**
1. Create a new scene and set it to show up a message dialogue.
2. Type in Japanese characters (longer the better). If using a non-multibyte character supported environment, just copy & paste a dummy text such as "あいうえおかきくけこさしすせそ".
3. Observe the unwanted blank spacings between the end of string and the current caret position.
4. Now, try to locate and set the caret to somewhere in the middle of the string, such as between "き" and "く".
5. Type in a character or letter (i.e. "a")
6. Observe the entered letter inserted at a different position. In this case, the typed in character "a" will be inserted at a different position where the caret is not located.

**Expected behavior**
The letter should be inserted at the specified position where the caret is currently located.

**Platform (please complete the following information):**
 - OS: Windows 11, MacOS 13, 14
 - App version: 4.0 (Seen in 3.x as well)

**Additional context**
This issue may be coming from Electron it self.

**Comment by chrismaltby** [comment] 2024-06-27 10:33
Hi @tomo666 that's odd I can't seem to replicate this issue at my end following the steps you listed (I'm running macOS 13.5.1)

https://github.com/chrismaltby/gb-studio/assets/16776042/ee339192-3a3d-4094-82c7-ef4328873798

am I missing something in this video?

I can completely understand how this is COULD happen though, both this input and the math equation input are built on top of [React Mentions](https://github.com/signavio/react-mentions) which handles the autocomplete/text code menus as well as highlighting tokens such as variables. And the way that component works is it has a hidden text area that is where you're actually typing (and that handles the caret position / text selection), and a layer of HTML displayed over the top that shows identical content (but with syntax highlighting), the textarea and HTML are supposed to have the EXACT same position of every character and if they were out of sync somehow then what you're seeing would happen. I could imagine that the HTML layer is showing the multibyte characters, but maybe the textarea is editing them as individual bytes causing the text selection width to be wider than the display width, that's just a guess though.

Could you maybe attach a zip of an affected project? Maybe even though I can't reproduce the error I will see it if I open an affected project file.

Thanks

**Comment by tomo666** [comment] 2024-06-27 10:57
Hi @chrismaltby, thanks for looking into this issue and for your insights.
Please find the test project here:
[Caret_Test.zip](https://github.com/user-attachments/files/16012292/Caret_Test.zip)

It's just a plain new project with scene added with a message dialogue event attached.
Before I've reported this issue, I did some surveys in a Japanese discord thread and asked around few Japanese GBS users and they all seem to have the same issue. Not only Windows but on a Mac too.
Note that some user reported that this issue was not present until version 3.x and was working well in 2.x. I thought it might be something to do with the Electron version as I saw few issues searching around related to multi-lang support with this tool, but since I don't know much around the Electron/NodeJS stuff I'm a bit out of expert here.
If you need anything else, please let me know 🙂

**Comment by chrismaltby** [comment] 2024-06-27 14:09
Thanks for this @tomo666 unfortunately your project works fine for me too, I've tried setting my macOS to use Japanese input hoping that might help but no difference. I've also tried on Windows 10 and it was working fine there too :-(

To help understand what's going on I've made a debug build that makes it so the Textarea and HTML are both visible and displayed simultaneously one above the other. See in this screenshot the white form input at the bottom is where you're actually typing and the dark text at the top is the HTML which is normally the only visible part.

<img width="468" alt="Screenshot 2024-06-27 at 14 57 34" src="https://github.com/chrismaltby/gb-studio/assets/16776042/175cd2a1-8a06-49d6-9dad-97f028fcb392">

In my testing the characters are always aligned perfectly horizontally so when overlaid on top of each other, each character would appear in the same location.

You can get the debug build here: https://github.com/chrismaltby/gb-studio/actions/runs/9697921855

My theory is that for you one of those will look different to the other in some way that will help us identify the cause of the problem. If you could try testing that build and attach some screenshots that would be really useful. Thanks

**Comment by chrismaltby** [comment] 2024-07-02 15:40
Thanks @tomo666 that is strange, the font is definitely different in textareas in yours, odd that Latin characters are appearing thinner and Japanese ones are wider too.

Looking into it I noticed the HTML preview had some CSS `font-variant-east-asian: normal;` that the textarea didn't include, not sure if that's it but worth trying. I've tried explicitly setting all the font CSS fields to be identical, hoping that might improve things.

If you want to try this version instead you can download at
https://github.com/chrismaltby/gb-studio/actions/runs/9763711155

I've also enabled the developer tools so you can play around with the HTML too

**Comment by chrismaltby** [comment] 2024-07-03 09:50
Hi @tomo666 I've managed to get a machine configured to use Japanese in a way that reproduces the text issues you were seeing and believe I have a fix in place for this now. 

This is included in the latest dev build available at:
https://github.com/chrismaltby/gb-studio/actions/runs/9775487285
and will be part of the next release.

I'll close this issue for now but if this version isn't working for you feel free to reopen it.
Thanks again for all the information you've provided to help locate the cause of this problem.

**Closed** 2024-07-03 09:52 UTC
Labels: bug

**Comment by tomo666** [comment] 2024-07-03 16:12
Thanks @chrismaltby !!
I've confirmed fixed on both Mac & Windows (Intel ver for now) on my side.
This fix was actually a big improvement for us Japanese users as it was long waited for an update (and for someone to report the issue too 😂). So many thanks to you for putting the effort into setting up an environment to reproduce & fix this issue.
