### ISSUE TITLE
[ Question ] Is it possible to an Actor animate while standing still?

### ISSUE THREAD

**Issue by rafaeldcastro** [chrismaltby/gb-studio#47] opened 2019-04-24 16:47 UTC
Is it possible to an Actor animate while standing still?

Like an npc who walks in the same place

**Comment by chrismaltby** [comment] 2019-04-24 17:06
Looking it that :-) this is a duplicate of https://github.com/chrismaltby/gb-studio/issues/8

**Closed by chrismaltby** 2019-04-24 17:06 UTC
