### ISSUE TITLE
Interacting with actors permanently removes the overlay

### ISSUE THREAD

**Issue by DuendeInexistente** [chrismaltby/gb-studio#154] opened 2019-05-13 13:34 UTC
**Note: for support questions, please use one of the following channels**.

Reddit: [/r/gbstudio](https://www.reddit.com/r/gbstudio)
Discord: [Join Chat](https://discord.gg/bxerKnc)

This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - [X] bug report
  - [ ] feature request
  - [ ] support request

* **What is the current behavior?**
Interacting with actors removes the overlay and doesn't reapply it.
At first I thought it was related to text boxes, but it seems to be on all actor interaction, even if the actors have no actual scripting.
Curiously, the overlay seems to very quickly descend off the screen.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Cover part of the screen with an overlay, and interact with an actor.

* **What is the expected behavior?**
The overlay should automatically return to its previous settings.

* **Please tell us about your environment:**

  - Version: Latest automatic dev release
  - Platform: Linux

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
[A video of the error.](https://files.catbox.moe/qek2ac.mp4) The overlay can be seen descending diagonally at 00:50

**Comment by chrismaltby** [comment] 2019-05-13 13:52
I'm not able to reproduce the issue from your video where interacting with an actor with no script causes the overlay to disappear. Could you maybe post a copy of your project (with just that scene included) so I can see what's happening there?

**Comment by DuendeInexistente** [comment] 2019-05-13 14:03
Sure, [here is the rom](https://files.catbox.moe/syyfa7.7z), and [the project](https://files.catbox.moe/lar06y.7z). Press the up arrow in the rom to unhide some actors.

**Comment by chrismaltby** [comment] 2019-05-13 15:04
Thanks, so there was two parts to this:

1) the overlay closing when you interacted with anyone was a definite bug (in-fact you didn't even need an actor, if you viewed any text box, then opened an overlay, then pressed A anywhere it would close the overlay because it thought the text box was still open) I've fixed this as of 7d84767fd51054bb8ccc30e6d408b65e2e187e31

2) The overlay returning to it's previous position and keeping whatever settings you stored on it and the colour you used is a little more awkward and not I'm not yet 100% sure this should be the default behaviour (need to think about it more). For now you might just need to add some code to reset the overlay after the dialogue is finished. You could maybe have a hidden actor with the script and logic for positioning the overlay and then use "Actor: Invoke Script" to use it almost like a function, saving you rewriting it each time. I've made that change in this version, check out the button script, how it calls a function on the invisible actor in the corner
[lar06y_overlayreset.zip](https://github.com/chrismaltby/gb-studio/files/3173529/lar06y_overlayreset.zip)

**Closed** 2024-09-05 10:26 UTC
