### ISSUE TITLE
[BUG] Game World doesn't remain zoomed after switching from other GB Studio screens

### ISSUE THREAD

**Issue by jrmysrss** [chrismaltby/gb-studio#45] opened 2019-04-24 14:47 UTC
**MacOS version of GB Studio**

Note the screenshot where the zoom is set to 800% but the Game World appears to be 100%. Clears up after clicking the zoom buttons.

![Screen Shot 2019-04-24 at 9 45 10 AM](https://user-images.githubusercontent.com/19714107/56668742-ad86a500-6675-11e9-993d-8ace8c21a4c8.png)

**Comment by chrismaltby** [comment] 2019-04-24 14:56
Thanks but this is a duplicate of https://github.com/chrismaltby/gb-studio/issues/14 and is now fixed in  develop branch from commit c1dc58a

**Closed by chrismaltby** 2019-04-24 14:56 UTC
