### ISSUE TITLE
Adding Save and Load?

### ISSUE THREAD

**Issue by Audio-Rochey** [chrismaltby/gb-studio#62] opened 2019-04-25 19:44 UTC
Chris,

excellent work. I am having a blast learning pixel art, tiling and even blowing out the cobwebs on MOD files for music. Some of the limitations in the engine are really what makes it engaging. Quick success is easy to get, and the next feature always feels like it could be just over the next hill.

I have no idea where to begin with contributing to code, but let me ask, is there any method to create "Save games?" The bigger we make a game, the harder it is to expect players to go all the way through in one sitting.

Cheers

Rochey

**Comment by thomas-alrek** [comment] 2019-04-25 19:57
Possibly a duplicate of #5 ?

**Comment by Audio-Rochey** [comment] 2019-04-25 20:16
Thomas - yup. sounds like a duplicate.
How do I get the latest build? assuming it's not on the website, i have to clone and build myself?

**Comment by chrismaltby** [comment] 2019-04-25 20:31
Hi Rochey,
I'm really glad you're enjoying using this. I hope the game that you're making for your kids birthday is going well!
For now to have saving/loading you would need to clone, switch to the `develop` branch and build yourself. You would need a recent version of nodejs and yarn installed. I want to get through a few more of the issues people are having before pushing out another release. No ETA on that just yet as work's pretty busy for me right now so not getting as much time as I'd like to work through the list.
Closing as it is a duplicate of #5

**Closed by chrismaltby** 2019-04-25 20:31 UTC

**Comment by Audio-Rochey** [comment] 2019-04-25 20:35
Cheers Chris, I can wait for a save-game function, as long as the files are compatible.
Is there a better forum you know of to discuss the game-dev'ing side of the house? Where can the fans of your work chat about it?
Also, have you seen twitter? the Japanese have gone NUTS about GB STudio.

**Comment by thomas-alrek** [comment] 2019-04-25 22:06
Maybe it would be a good idea to create a Discord channel, and/or a dedicated subreddit for this?

**Comment by WAUthethird** [comment] 2019-04-25 22:44
> Maybe it would be a good idea to create a Discord channel, and/or a dedicated subreddit for this?

[Created.](https://discord.gg/hwCbT5p)
Keep in mind that I just barely created this, a fair bit of configuration still needs to be done.

**Comment by chrismaltby** [comment] 2019-04-25 22:48
I already made one 😬 https://discord.gg/bxerKnc

**Comment by WAUthethird** [comment] 2019-04-25 22:48
oof
ok, deleting then.

**Comment by chrismaltby** [comment] 2019-04-25 22:49
No worries, was just going to bed and was going to share in the morning!

**Comment by WAUthethird** [comment] 2019-04-25 23:32
> No worries, was just going to bed and was going to share in the morning!

Then if you don't mind, I'll make the subreddit.
...Unless you're going to do that?

**Comment by chrismaltby** [comment] 2019-04-26 12:02
Thanks William. Can you make me a moderator on /r/gbstudio? My username is eldritch_holla
